# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_auto_20191023_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='qr',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
